### ISSUE TITLE
It does not open (v4.3.4)

### ISSUE THREAD

**Issue by yisus1313** [namreeb/wowned#10] opened 2017-12-13 22:37 UTC
In version 3.3.5 works perfect but when trying to open wow.exe in expansion 4.3.4 (Server GPLP Guerreros Por La Paz)  does not open, it only says that the process has started but nothing happens.
I tried several Cataclysm servers but it is the same, the WoW does not open.
Yes you can update or see that it works correctly in Cataclyms I would be grateful.

**Comment by namreeb** [comment] 2017-12-13 23:50
Duplicate of #3

**Closed as completed by namreeb** 2017-12-13 23:50 UTC
Labels: duplicate
